### ISSUE TITLE
Add additional sources

### ISSUE THREAD

**Issue by victorpimentel** [victorpimentel/TVShows#1]
For when EZRSS/ShowRSS is not updating.

**Comment by meirka** [comment]
Nice idea, have you thought to create rss parser or something like that so that if there are no RSS feeds available ( online ) then application can gather information on it's own?

**Comment by victorpimentel** [comment]
There is initial work for adding custom RSS, but nothing to add "from a page". Given the null stability of the sources maybe that is the way to go, but maybe it's too much. We'll see this summer.

Anyway this is something to be added in the future. In the near future there are things more important (i.e. fixing bugs!).
