### ISSUE TITLE
Option to sort content in folders

### ISSUE THREAD

**Issue by LadyMadonna** [victorpimentel/TVShows#14]
For example, episodes from show A would download to folder A, episodes from show B would download to folder B.

**Comment by tcard** [comment]
I'll take care of it if you don't mind!

**Comment by victorpimentel** [comment]
It would be awesome, @tcard :)

But there are two ways to do this:
- Automatically choosing where to download the torrent -> getting the show name and creating a folder. Not very difficult, I think.
- Or the user chooses a custom folder for each show. Maybe the folders are populated automatically, but there is an option for the user to change the name.

The second approach is more powerful, but the way I see this the CoreData backend needs to be changed. That way, Subscriptions need a new field for storing the custom folder. I'm pretty new to CoreData, but by default a change in the model makes it incompatible with the previous stored subscriptions. Initial research tells me that it is possible to automatically "migrate" CoreData models, but it needs a little work:

http://developer.apple.com/library/mac/#documentation/Cocoa/Conceptual/CoreDataVersioning/Introduction/Introduction.html
http://www.timisted.net/blog/archive/core-data-migration/
http://stackoverflow.com/questions/1018155/what-do-i-have-to-do-to-get-core-data-to-automatically-migrate-models/1219911#1219911

I don't know how long it would take to change this (it could be trivial following those instructions, or it could be difficult based on our messed up managed objects). Anyway this is something that needs to be addressed (the model should not be set in stone, I need to add more attributes for other things), so @tcard if you want to contribute this is the most important thing right now :)

**Comment by tcard** [comment]
I'll take a look at it, although I don't think it's necessary to ask the user for a custom folder name in this particular case. I happen to be actually pretty new to Obj-C, so going deeper is always interesting.
