### ISSUE TITLE
The ability to turn on and off automatically

### ISSUE THREAD

**Issue by ErniePC12** [victorpimentel/TVShows#16]
In the past, I was able to create a Launchd job that would run a script every 30 minutes. This script woud check the time of day, and if it was Monday through Friday during work hours, it would disable the Launchd job for TVShows.  

I only want to have this run while I'm not at work.  I don't think that this is working with the new version since the change in management.

**Comment by victorpimentel** [comment]
If you want to programatically disable TVShows you can unload it this way:

```
launchctl unload -w ~/Library/LaunchAgents/com.victorpimentel.TVShowsHelper.plist
```

And later enable it again with:

```
launchctl load -w ~/Library/LaunchAgents/com.victorpimentel.TVShowsHelper.plist
```

Is there anything else that you need?

**Comment by ErniePC12** [comment]
Ah, I see what you did there.  I didn't change the file name from embercode to victorpimentel.

OK, that works.  I should have put 2+2 together when I looked in the LaunchAgents folder...

I checked, and my script works.  And I like that I can now see in the menu bar that it works.  Thanks!
