### ISSUE TITLE
Preventing accidentally unsubscribing

### ISSUE THREAD

**Issue by LadyMadonna** [victorpimentel/TVShows#17]
Make unsubscribing not so easy to do by accident. Now if you accidentally click on the unsubscribe button the show disappears, and there's no undo option.

I see two ways we can improve this: by making the unsubscribe button more noticeable (red, bold letters...), more different to the "close" button, and/or by displaying a warning if the user clicks on the button and asking for confirmation (this warning should be optional).

**Comment by victorpimentel** [comment]
I think a confirmation window should be better, but I don't think the warning should be optional. Adding another option for that is overkill. Anyway, that is a button that will be pressed very few times.

**Comment by LadyMadonna** [comment]
Maybe a "Never remind me again" checkbox? I don't know...
