### ISSUE TITLE
Doesn't download shows :C

### ISSUE THREAD

**Issue by marmi** [victorpimentel/TVShows#19]
Hi, I was all cheered up when I knew abour the resucitation of TVshows. Upfront, thank you very much. Little problem that I have: I cannot get it working. The panel installs all right, subscriptions can be set, and shows can be downloaded directly pressing the "direct download" arrow. However, the shows do not download automatically. The activity always gives the same error: 

Could not write to ~/Library/LaunchAgents/com.victorpimentel.TVShowsHelper

I have tried ununstalling and reinstalling several times, for current user or for all users, it is always the same. com.victorpimentel.TVShowsHelper never installs in that path nor elsewhere. Any hints?

**Comment by victorpimentel** [comment]
This is a strange thing. Did you change ~/Library/LaunchAgents/ permissions? Try to fix them by writing this in Terminal.app:

```
chmod 755 ~/Library/LaunchAgents/
```

And then try again.

**Comment by marmi** [comment]
MacBook-Air-de-marmi:~ marmi$ chmod 755 ~/Library/LaunchAgents/
chmod: /Users/marmi/Library/LaunchAgents/: No such file or directory

LaunchAgents folder is not in my home directory but in the system directory. It does have the right permissions.
Thanks for the support!

**Comment by victorpimentel** [comment]
Then execute this to create the folder and all will be fine:

```
mkdir  ~/Library/LaunchAgents/
```

It is strange that the folder did not exists, did you delete it? Anyway, I'll have to fix it in the code to cover this case. Thanks for the reporting!

**Comment by marmi** [comment]
You got it, works all right now. FINALLY I don't think that I deleted it, in any case it wasn't re-created at multiple reinstalls. Thank you so much, fantastic application and fantastic support
