### ISSUE TITLE
Can't pick "start from episode".

### ISSUE THREAD

**Issue by meirka** [victorpimentel/TVShows#22]
Why I can't pick "start from episode" in subscription preferences? Is it a bug or?

Thank you for supporting PPC.

**Comment by LadyMadonna** [comment]
You can't because it doesn't find any episodes to start from, it's a bug we have detected in PPC :( If you need to use TVShows on a PPC please downgrade to beta 7 until we find a fix ;)

**Comment by meirka** [comment]
Got it, thank you!

**Comment by LadyMadonna** [comment]
Hi Meirka,

We just released a new beta that fixes the PPC bug. You can update from the app or download it from [our web](http://tvshowsapp.com/TVShows.zip) ;)

**Comment by meirka** [comment]
Doesn't seem to do the trick. I can see shows ( by the way not all that used to be, did you guys change feed? ) but I can not pick episode to  start from. Sorry to bring bad news :(

I'll be happy to test any releases for you.

**Comment by victorpimentel** [comment]
When you select a show you have to wait a little more because, since we use several sources at the same time, it takes a couple of seconds more to load the episode list.

And it should be more shows than before (but cancelled shows are now removed from the list).

**Comment by meirka** [comment]
When I add subscription I don't see the list of episodes to start from. For example Conan show, it just gives option to start from the next show. Now the once I am already subscribed have mixed results, some have previous episodes, others don't. For example "Top Gear" doesn't but "Big bang theory" does. 

So in some cases it works, in others it doesn't.
Thanks.

**Comment by meirka** [comment]
P.S: Forgot to mention, I did wait for a while... but episodes don't come up.

**Comment by LadyMadonna** [comment]
Hi meirka, does this still happen? We haven't had reports from anyone else, it's strange... have you reloaded the show list? It's needed to reload the feeds.

**Comment by meirka** [comment]
Ok, I reloaded show list and it works 100%. I guess I had to remove and add TV shows. Thank you.
