### ISSUE TITLE
show pictures not available?

### ISSUE THREAD

**Issue by gatogatogato** [victorpimentel/TVShows#23]
I can't see any pictures for the shows in any window: 

http://imageshack.us/photo/my-images/97/bildschirmfoto20110627un.png/ 
http://imageshack.us/photo/my-images/26/bildschirmfoto20110627uh.png/

No error or warnings in the TVShows log or in the system log. What can I do?

**Comment by victorpimentel** [comment]
Close the preference pane, try to delete the folder ~/Library/Application Support/TVShows 2/Cache/ and reopen the System Preferences.app. After some seconds the covers should appear.

In the future the app should detect that a cover was not properly downloaded and in that case try to download again that cover.

**Comment by gatogatogato** [comment]
Covers were reloaded but seem to be emtpy:

http://imageshack.us/f/847/bildschirmfoto20110627u.png/

**Comment by victorpimentel** [comment]
Mmm, strange, can you visit this site?

http://www.thetvdb.com/

Covers are downloaded from there, I tried now and they all download just fine. If you use LittleSnitch or another firewall please give access to them. Can you try adding another show?

**Comment by gatogatogato** [comment]
Just found the problem. 
I use the adblocking software from http://glimmerblocker.org/ 
Works as a local proxy - really great software usually, but this time it really annoyed me.
There is one rule that blocks all URLs containing "banners" - thetvdb.com guys store their pics in exactly that path :(

Thanks for the support anyway!
