### ISSUE TITLE
OS X 10.7 Lion GM Core data alert / NSAlert background warning

### ISSUE THREAD

**Issue by gabek** [victorpimentel/TVShows#24]
I just recieved an error message outside of TVShows (wasn't within the prefpane) saying that the model is a different version of the store.  I couldn't tell what app was alerting me of this so I checked my logs and saw that TVShows was popping up the UIAlert  box along with a message saying it couldn't find the NSManagedObjectModel.  Makes sense if there's a core data issue I suppose.

7/3/11 10:59:05.976 PM TVShowsHelper: NSAlert is being used from a background thread, which is not safe.  This is probably going to crash sometimes. Break on _NSAlertWarnUnsafeBackgroundThreadUsage to debug.  This will be logged only once.  This may break in the future.
7/3/11 11:02:44.915 PM TVShowsHelper: An uncaught exception was raised
7/3/11 11:02:44.916 PM TVShowsHelper: +entityForName: could not locate an NSManagedObjectModel for entity name 'Subscription'
7/3/11 11:02:44.951 PM TVShowsHelper: (
    0   CoreFoundation                      0x00007fff92726986 __exceptionPreprocess + 198
    1   libobjc.A.dylib                     0x00007fff921e1d5e objc_exception_throw + 43
    2   CoreData                            0x00007fff8db8c929 +[NSEntityDescription entityForName:inManagedObjectContext:] + 153
    3   TVShowsHelper                       0x00000001000179b4 -[TVShowsHelper checkAllShows] + 379
    4   Foundation                          0x00007fff8ca27a00 __NSFireTimer + 102
    5   CoreFoundation                      0x00007fff926db694 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
    6   CoreFoundation                      0x00007fff926db1e6 **CFRunLoopDoTimer + 534
    7   CoreFoundation                      0x00007fff926bbba1 __CFRunLoopRun + 1617
    8   CoreFoundation                      0x00007fff926bb216 CFRunLoopRunSpecific + 230
    9   Foundation                          0x00007fff8c9db983 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 267
    10  Foundation                          0x00007fff8c9db86f -[NSRunLoop(NSRunLoop) run] + 62
    11  TVShowsHelper                       0x00000001000158e5 -[TVShowsHelper runLoop] + 279
    12  Foundation                          0x00007fff8ca2a1ea -[NSThread main] + 68
    13  Foundation                          0x00007fff8ca2a162 __NSThread__main** + 1575
    14  libsystem_c.dylib                   0x00007fff924288bf _pthread_start + 335
    15  libsystem_c.dylib                   0x00007fff9242bb75 thread_start + 13
)
7/3/11 11:02:44.951 PM TVShowsHelper: **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+entityForName: could not locate an NSManagedObjectModel for entity name 'Subscription''
**\* First throw call stack:
(
    0   CoreFoundation                      0x00007fff92726986 __exceptionPreprocess + 198
    1   libobjc.A.dylib                     0x00007fff921e1d5e objc_exception_throw + 43
    2   CoreData                            0x00007fff8db8c929 +[NSEntityDescription entityForName:inManagedObjectContext:] + 153
    3   TVShowsHelper                       0x00000001000179b4 -[TVShowsHelper checkAllShows] + 379
    4   Foundation                          0x00007fff8ca27a00 __NSFireTimer + 102
    5   CoreFoundation                      0x00007fff926db694 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
    6   CoreFoundation                      0x00007fff926db1e6 **CFRunLoopDoTimer + 534
    7   CoreFoundation                      0x00007fff926bbba1 __CFRunLoopRun + 1617
    8   CoreFoundation                      0x00007fff926bb216 CFRunLoopRunSpecific + 230
    9   Foundation                          0x00007fff8c9db983 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 267
    10  Foundation                          0x00007fff8c9db86f -[NSRunLoop(NSRunLoop) run] + 62
    11  TVShowsHelper                       0x00000001000158e5 -[TVShowsHelper runLoop] + 279
    12  Foundation                          0x00007fff8ca2a1ea -[NSThread main] + 68
    13  Foundation                          0x00007fff8ca2a162 __NSThread__main** + 1575
    14  libsystem_c.dylib                   0x00007fff924288bf _pthread_start + 335
    15  libsystem_c.dylib                   0x00007fff9242bb75 thread_start + 13
)
7/3/11 11:02:44.951 PM com.victorpimentel.TVShowsHelper: terminate called throwing an exception
7/3/11 11:02:49.440 PM com.apple.launchd.peruser.501: (com.victorpimentel.TVShowsHelper[242]) Job appears to have crashed: Abort trap: 6
7/3/11 11:02:50.207 PM ReportCrash: Saved crash report for TVShowsHelper[242] version 2.0b9 (532) to /Users/gabek/Library/Logs/DiagnosticReports/TVShowsHelper_2011-07-03-230250_Gabes-MacBook-Pro.crash

**Comment by victorpimentel** [comment]
Thanks for the report, I will be checking this when I install Lion :)

By the way, are you having this problem consistently or it was just this one time?

**Comment by gabek** [comment]
It was just this one time, but I wanted to capture the log just in case :)
