### ISSUE TITLE
Miso sync erases previous shows and create duplicates

### ISSUE THREAD

**Issue by Mortimerp9** [victorpimentel/TVShows#25]
Hi,

so I tried the new Miso sync feature, added a few shows on my new Miso account (I wasn't a user before) and then setup the connection in TVShows2.

It synched with Miso but then the shows I had already in TVShows but not yet added in Miso were removed and some that were both in Miso and in TVShows appeared as duplicate.

**Comment by victorpimentel** [comment]
Hi Mortimerp9, hi for the report. Several people have reported this, we do no know exactly what it's happening with that. It seems that in the middle of the Miso sync it just stops syncing, so the next sync it removes the shows that aren't on Miso.

The duplicates are another issue, and I bet that it has to be related with Core Data :/ We'll try to fix these issues, but I'm afraid I have to rewrite the Core Data code to fix them.

By the way, if you want to see which shows were unsubscribed, the logs will have them listed (about tab->show logs button).

Sorry for the inconveniences.

**Comment by victorpimentel** [comment]
This doesn't happen any more since the Sync feature it only adds new subscriptions now, it doesn't delete any.
