### ISSUE TITLE
Support for ev0.in

### ISSUE THREAD

**Issue by MaDDoGo** [victorpimentel/TVShows#29]
Hi,

I'm not using torrents and I want to know if it will be possible to add support to ev0.in, this is a website with RSS with lastest shows with DD's links.

Thanks and great job.

**Comment by LadyMadonna** [comment]
Hi MaDDoGo,

I'm sorry but we're not planning on adding direct download support in TVShows. Direct downloads have some legal and technical implications that we aren't willing to deal with for the moment.

If you use JDownloader to manage your downloads, take a look at this plugin, which lets you download content automatically from RSS feeds: http://jdfeedme.wordpress.com/

**Comment by MaDDoGo** [comment]
Ok, I tought that torrent and direct downloads was the same thing legally. 

I'll take a look at the jdownloader plugin, thanks!
