### ISSUE TITLE
Fix feeds without dates

### ISSUE THREAD

**Issue by victorpimentel** [victorpimentel/TVShows#32]
Right now if a feed does not have any date, the application will set a custom date equally for all episodes. In the end, this results on randomly ordered items.

A solution would be to generate slightly different dates based on the season and episode number (for example adding as many minutes as seasons and as many seconds as episodes. That way all episodes would be ordered by season/episode.

**Comment by dustinrue** [comment]
Could you not get the original air date of the episode after looking it up?
