### ISSUE TITLE
Save show in its own folder saves the torrent before creating the folder

### ISSUE THREAD

**Issue by LadyMadonna** [victorpimentel/TVShows#34]
It seems that when the show/season folder doesn't exist, the episode torrent is downloaded faster than the folder is created, so it is stored in the default destination folder instead of the show/season folder.

If the folder doesn't exist, TVShows should wait for N seconds before downloading the torrent, so the folder gets created in time.

Reported by vbadtz in the [support forum](http://support.tvshowsapp.com/discussions/problems/154-save-each-show-in-its-own-folder).

**Comment by victorpimentel** [comment]
Mmm, this doesn't make any sense at all. Before saving any torrent first the correct folder is created:

https://github.com/victorpimentel/TVShows/blob/master/Classes/TSTorrentFunctions.m#L211

I'm not saying that there are no bugs in there, but even then, it doesn't make any sense. If the folder is not created then the torrent file will not be saved at all.

I would bet all my money that this user has told Transmission to move ongoing torrents to other location (and/or that the final location is not "Same as in torrent file").

**Comment by LadyMadonna** [comment]
Quoting from the user: "Transmission IS set to "download to the same destination folder as the torrent"." I don't know what's happening, I just tried with some shows in my TVShows and it works for me. But there's not a "folder created" message in the log, so asking for the user's log would not help us at all.
