### ISSUE TITLE
JSONValue Error, TV Show Menu Greys out

### ISSUE THREAD

**Issue by chrisgeo** [victorpimentel/TVShows#38]
Looks like I've been getting a lot of these:

```
2/29/12 4:44:09.214  TVShowsHelper: -JSONValue failed. Error trace is: (
    Error Domain=org.brautaset.JSON.ErrorDomain Code=3 "Unrecognised leading character" UserInfo=0x10125a5a0     {NSLocalizedDescription=Unrecognised leading character}
)
```

Which (seems to?) leads to a lot of this:

![Grey'd out menu](http://f.cl.ly/items/0j3C0M2C0y0G0u0H0L2J/tvshowsbug.png)

**Comment by victorpimentel** [comment]
Hi chrisgeo,

Have you enabled Miso? If so, try to disable it and reenable it :/

**Comment by chrisgeo** [comment]
Next time it happens, I definitely will. I recently had to rebuild my box so I haven't seen it!

**Comment by chrisgeo** [comment]
Looks like so far, it's ok. I'll close this issue and see if when the next time it happens, what service calls, etc it's making to track down the problem.
