### ISSUE TITLE
crashes Prefs page on 10.8 DP3 after you add the second subscription

### ISSUE THREAD

**Issue by ssbarnea** [victorpimentel/TVShows#45]
Initially it worked, until I added the second subscription. Now it always crashes the prefpane so I will have to remove it :(

Here is the crash log http://pastebin.com/raw.php?i=M8KKYrha

**Comment by ssbarnea** [comment]
Update: this happens when I add Simpsons with the oldest episode as being the first to be downloaded. HD enabled. 

I tried with others it seems to work with some of them, anyway the success ratio is ~20%.

Here is another crash, maybe it helps http://pastebin.com/AD1AwBgv

**Comment by LadyMadonna** [comment]
Hi ssbarnea,

Thank you for reporting it, but we're not testing TVShows in Mountain Lion yet so we cannot solve this for the moment.

Sorry for the inconvenience.
