### ISSUE TITLE
TvShows downloads std version even with HD checkbox

### ISSUE THREAD

**Issue by carlosedp** [victorpimentel/TVShows#47]
For some shows, TvShows app downloads the standard definition episode instead of downloading the HD version.

I have the 2.0RC2 version and the HD checkbox is ticked.

**Comment by carlosedp** [comment]
I think this commit fixes the issue:

https://github.com/kariudo/TVShows/commit/b36a6c73fd927c9a02ec211cce3d8dca437cbf22

Except that episodes with x264 can be SD as well.

**Comment by LadyMadonna** [comment]
Hi carlosedp,

The commit you link isn't ours, in fact it reverts a commit we did back in February when .mp4 files became the standard for SD files to avoid mistakenly downloading them as HD files.

Please keep in mind that TVShows has a timeout after which if the preferred version (HD in your case) isn't available, it downloads any other version (SD in your case). So it can be normal that it sometimes downloads SD episodes. You can change the timeout via the terminal, it's explained in our [support page](http://support.tvshowsapp.com/kb/tvshows-customization/advanced-customization). If you want us to look into your case you can open a new discussion at our support page, attaching the log (About tab -> View logs) and provide some examples of shows downloaded in SD.

**Comment by carlosedp** [comment]
So maybe what happened is the timeout that fired the SD download.

Sorry about the confusion. Thanks.
