### ISSUE TITLE
launchctl: Dubious permissions on file (skipping)

### ISSUE THREAD

**Issue by seandunaway** [victorpimentel/TVShows#49]
Menu icon was not showing up and TVShows 2 was not checking for new episodes.

$ launchctl load ~/Library/LaunchAgents/com.victorpimentel.TVShowsHelper.plist
launchctl: Dubious permissions on file (skipping): /Users/x/Library/LaunchAgents/com.victorpimentel.TVShowsHelper.plist

This fixed it:
$ chmod 755 ~/Library/LaunchAgents/com.victorpimentel.TVShowsHelper.plist

Working great now.  Thanks for this great program. :)

**Comment by LadyMadonna** [comment]
Thanks for reporting.
