### ISSUE TITLE
G4-G5 support

### ISSUE THREAD

**Issue by meirka** [victorpimentel/TVShows#5]
Please can you make universal app, so it works on G4 and G5 machines.
Thank you.

**Comment by victorpimentel** [comment]
Oh, sorry, that was my fault. Next version will be universal.
Actually, can you test if this one is working fine?
https://github.com/downloads/victorpimentel/TVShows/TVShows_2.0b6-universal.zip

**Comment by meirka** [comment]
Ok, checked it works. Everything seems to be functioning just fine. It adds subscriptions, shows descriptions and images. The only thing I haven't check if it updates show list from the feed. 

I think this this should be a separate request for update buttom.
