### ISSUE TITLE
crash when adding new show on mountain lion

### ISSUE THREAD

**Issue by DonMagee** [victorpimentel/TVShows#51]
When adding a new show on mountain lion the control panel crashes. The show is added even though the app crashes. 

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: EXC_I386_GPFLT

Application Specific Information:
objc_msgSend() selector name: timeIntervalSinceReferenceDate
com.victorpimentel.TVShows2 v.604 (TVShows)
objc[2561]: GC: forcing GC OFF because OBJC_DISABLE_GC is set
Performing @selector(subscribeToShow:) from sender NSButton 0x7fa6d32f7ff0

**Comment by rubenfonseca** [comment]
having exactly the same problem

**Comment by victorpimentel** [comment]
Fixed in 9f5c97f3
