### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by corysimmons** [victorpimentel/TVShows#78]
Last TVShows version was Nov. 18, 2013. Lots of open issues. What's the deal?

**Comment by tekGuy64** [comment]
Bump

**Comment by tovkal** [comment]
Clearly Victor is not developing the project anymore, though it looks like he still maintains the website and server

**Comment by sdecandelario** [comment]
And any is thinking about fork it?

**Comment by ilucas** [comment]
I´m working on a fork. but there's not much. yet.

**Comment by sdecandelario** [comment]
Okey @ilucas i follow you repo for future news :)

**Comment by josephworld** [comment]
I will fllow the fork. thanks.

On Thursday, April 9, 2015, Sergio notifications@github.com wrote:

> Okey @ilucas https://github.com/ilucas i follow you repo for future
> news :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/victorpimentel/TVShows/issues/78#issuecomment-91141553
> .

## 

Sent from Mobile Phone

**Comment by deandmx** [comment]
Use this instead: https://sonarr.tv

**Comment by sdecandelario** [comment]
Yes @deandmx from a while i'm using Sonarr and Im so happy :smile:

**Comment by arjunmayilvaganan** [comment]
@deandmx @sdecandelario Installed Sonarr from your suggestions. Sonarr working in El Capitan? It's not even opening for me in 10.11.

**Comment by tomtclai** [comment]
@arjunmayilvaganan Am on el capitan. Yes it does not show. I went to the browser and type http://localhost:8989 and interact with the app from there.

**Comment by tomtclai** [comment]
@arjunmayilvaganan am on el capitan. yes it does not show after opening. I go to http://localhost:8989 on a browser and interact with the app from there. Might work for you

**Comment by arjunmayilvaganan** [comment]
@tomtclai Wow. Thank you so much. It's running at http://localhost:8989. I thought it never opened and didn't know that it actually started but didn't display. Hope this will be fixed soon.

**Comment by asoksevil** [comment]
Sonnar doesn´t work for me and I just felt that TV Shows had a simpler and cleaner interface.

**Comment by jakeopolis** [comment]
@asoksevil try Otomatic (http://codingcurious.com/otomatic/). Unfortunately it's not free but it's dead simple to use and works perfectly.
