### ISSUE TITLE
Last Checked

### ISSUE THREAD

**Issue by meirka** [victorpimentel/TVShows#8]
Last checked says "never" and didn't update with in 14 hours. It is set to update every 15 minutes, however doesn't seem to work.

**Comment by victorpimentel** [comment]
It seems a bug present in the Universal build, but not in others. There is a quick fix, write this in the Terminal.app:

launchctl unload  ~/Library/LaunchAgents/com.victorpimentel.TVShowsHelper.plist
launchctl load  ~/Library/LaunchAgents/com.victorpimentel.TVShowsHelper.plist

I have to see why this is happening...

**Comment by meirka** [comment]
ok, I will check it out in the evening.

**Comment by victorpimentel** [comment]
Ok, there is a problem with Sparkle in PPC, the system used to update the application. I will fix it later, when I know how :)

**Comment by meirka** [comment]
Tried, yeah, didn't seem to do much.
What's sparkle? May be I can pick at it.

**Comment by victorpimentel** [comment]
Well, that upload is new. I mean, I uploaded it with the same name so other
users should download that version. Anyway the update is coming! To force
the update you can go to the Preferences and click "Check now".

Sparkle is a generic library used by many applications to handle updates :)

Vctor Pimentel
http://victorpimentel.com
